name: SonarCloud Analysis

on:
  push:
    branches: [ "4.7.0_battery" ]
  pull_request:
    branches: [ "4.7.0_battery" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: "4fc37f9f307bb3c3ba431be2c4456d5a0534b043"
        with:
          args: >
            -Dsonar.projectKey=hieunguyentt_TripTracker
            -Dsonar.organization=hieunguyentt
